version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
    - PYTHONUNBUFFERED=1

volumes:
  mongo_data: